### PR TITLE
add fart and lemonparty

### PR DESCRIPTION
**Pull request by txt3rob**
hopefully this will add the fart scroll and lemonparty

### CODE REVIEW

**Comment by evilsocket** [comment]
you've renamed one of the modules instead of creating a new one, and u didn't update the readme file ... i can't merge this.

**Comment by txt3rob** [comment]
will re do the fork and add them

**Comment by evilsocket** [comment]
:+1:

**Comment by evilsocket** [comment]
please remember to call your module with another name rather name HackTitle :D

**Pull request closed without merging**
